# -*- coding: utf-8 -*-
# config.py

WECHAT_WINDOW_TITLE = "微信"
DEFAULT_WINDOW_WIDTH = 1000
DEFAULT_WINDOW_HEIGHT = 800

INPUT_BOX_IMAGE = "search_contact.png"
CONFIDENCE_LEVEL = 0.8

RETRY_TIMES = 3
RETRY_DELAY = 1.0
POST_CLICK_DELAY = 0.5
PASTE_DELAY = 0.3
SCROLL_DELAY = 0.1

FAILSAFE_ENABLED = True