# -*- coding: utf-8 -*-
# config.py

WECHAT_WINDOW_TITLE = "微信"
DEFAULT_WINDOW_WIDTH = 1000
DEFAULT_WINDOW_HEIGHT = 800

INPUT_SEARCH_CONTACT = "search_contact.png"
INPUT_MESSAGE_IN = "message_in.png"
BTN_CONTACTS_IMAGE = "contacts.png"

CONFIDENCE_LEVEL = 0.8

RETRY_TIMES = 3
RETRY_DELAY = 1.0
POST_CLICK_DELAY = 0.5
PASTE_DELAY = 0.3
SCROLL_DELAY = 0.1

FAILSAFE_ENABLED = True

# chat_ocr_skill
CHAT_REGION_THRESHOLD = 30
CHAT_MIN_CONTOUR_AREA = 500
CHAT_OVERLAP_MAX_SEARCH = 800
CHAT_BLEND_WIDTH = 25
OCR_CONFIDENCE_THRESHOLD = 0.8

# agent / reddot_skill
AGENT_POLL_INTERVAL = 5.0
CHAT_LIST_WIDTH_RATIO = 0.30
CHAT_ITEM_HEIGHT = 64
CHAT_LIST_TOP_OFFSET = 90
CHAT_LIST_TAB_WIDTH = 0  # 聊天列表左侧的标签页宽度
RED_DOT_SAT_MIN = 80
RED_DOT_VAL_MIN = 80
RED_DOT_AREA_MIN = 35   # 小红点面积下限
RED_DOT_AREA_MAX = 45   # 小红点面积上限
RED_DOT_AREA_MIN2 = 150 # 大红点面积下限
RED_DOT_AREA_MAX2 = 160 # 大红点面积上限
RED_DOT_OFFSET_X = 20  # 小红点中心相对于聊天项右侧的水平偏移
RED_DOT_OFFSET_Y = 10  # 小红点中心相对于聊天项顶部的垂直偏移
RED_DOT_HUE_LOW1 = 0
RED_DOT_HUE_HIGH1 = 10
RED_DOT_HUE_LOW2 = 170
RED_DOT_HUE_HIGH2 = 180